- package-lock.json
- package.json
- src/components/Sidebar/index.jsx
- src/pages/product-list/index.jsx
- yarn.lock
> [P2-17] Products Feature, now user can see available products in product-list page

- src/pages/admin/login/index.jsx
> fix: fix login admin function

- src/components/Admin/NewTable/index.jsx
- src/pages/admin/daftar-produk/index.jsx
> [P2-40] See all product list (Admin)

- src/components/ProductCard/index.jsx
- src/components/Sidebar/index.jsx
- src/pages/product-list/index.jsx
> [P2-20] FEAT: now user can sort product list by its price or name

- next.config.js
- src/components/Admin/ModalTambahObat/index.jsx
- src/components/Nav/nav.jsx
- src/pages/admin/daftar-produk/index.jsx
> [P2-37] Admin Add Product Feature

- src/components/Admin/NewTable/index.jsx
- src/pages/admin/daftar-produk/index.jsx
> [P2-42] sort product list in admin

- src/components/Admin/DaftarObatTable/index.jsx
- src/components/Admin/ModalEditObat/index.jsx
- src/components/Admin/ModalTambahObat/index.jsx
- src/components/Admin/ModalTambahStok/index.jsx
> [P2-43] Admin Add Product Stock Feature, fix ModalEditProduk, ModalTambahProduk UI

- src/components/CheckOut/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/components/IsiTab/index.jsx
- src/components/Nav/nav.jsx
- src/components/ProductCard/index.jsx
- src/components/Sidebar/index.jsx
- src/pages/product-list/index.jsx
- src/pages/proses-pemesanan/index.jsx
> [P2-29] [P2-30] - User Transaction List Feature. Now user can see their past/current transaction list

- src/components/Cart/index.jsx
- src/components/CartProvider/index.jsx
- src/components/Nav/nav.jsx
- src/components/ProductCard/index.jsx
- src/pages/_app.jsx
- src/pages/keranjang/index.jsx
- src/redux/reducer/cart.js
- src/redux/store.js
> [P2-22] buy listed product

- src/components/CheckOut/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/components/DragAndDropZone/index.jsx
- src/pages/alamat/index.jsx
- src/pages/profile-page/index.jsx
- src/pages/proses-pemesanan/index.jsx
- src/pages/upload_resep/index.jsx
> [P2-28] Upload Resep Feature. User can now upload resep dokter and automatically added to proses-pemesanan page.

- src/components/Admin/DaftarObatTable/index.jsx
- src/components/Admin/StockHistoryTable/index.jsx
- src/pages/_app.jsx
- src/pages/admin/kartu-stok/[productId].jsx
> [P2-44] Admin Get ProductStockHistory Feature

- src/components/Admin/AdminNavbar/index.jsx
- src/components/Admin/AdminSidebar/index.jsx
- src/components/Admin/CardOrder/index.jsx
- src/components/Admin/ModalSalinanResep/index.jsx
- src/components/Admin/ModalTambahObat/index.jsx
- src/components/Admin/ModalTambahStok/index.jsx
- src/components/Footer/index.jsx
- src/pages/admin/dalam-pengiriman/index.jsx
- src/pages/admin/login/index.jsx
- src/pages/admin/pesanan-baru/index.jsx
- src/pages/admin/selesai/index.jsx
- src/pages/admin/siap-dikirim/index.jsx
@theodevoid @hasianamin ahihihi
> [P2-35] Admin Serve User Custom Order Feature

- src/components/Cart/index.jsx
- src/components/CheckOut/index.jsx
- src/components/Modal/index.jsx
- src/components/ModalAlamat/index.jsx
- src/components/Nav/nav.jsx
- src/components/PaymentMethod/index.jsx
- src/pages/checkout/index.jsx
- src/pages/keranjang/index.jsx
- src/pages/konfirmasi/index.jsx
- src/redux/reducer/cart.js
- src/redux/reducer/price.js
- src/redux/store.js
> FEAT: now user can change payment method in checkout page

- src/components/CheckOut/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/components/ProductCard/index.jsx
- src/components/modalUploadPembayaran/index.jsx
- src/pages/checkout/index.jsx
- src/pages/detail-transaksi/[transactionId].jsx
- src/pages/konfirmasi/index.jsx
- src/pages/proses-pemesanan/index.jsx
- yarn.lock
@hasianamin @theodevoid huhuhu
> [P2-27] User Upload Proof of Payment Feature

- src/components/Admin/AdminSidebar/index.jsx
- src/components/Admin/CardCategory/index.jsx
- src/components/Admin/CardStatistik/index.jsx
- src/components/Admin/CardWithCircularBar/index.jsx
- src/pages/admin/dashboard/index.jsx
- src/pages/admin/product-details/index.jsx
- src/pages/admin/ringkasan-statistik/index.jsx
- src/pages/product/[productId].jsx
> [P2-46] Sales Report

- src/components/Admin/IncomeStatement/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/pages/admin/kartu-stok/[productId].jsx
- src/pages/admin/laba-&-rugi/index.jsx
- src/pages/detail-transaksi/[transactionId].jsx
- src/pages/konfirmasi/index.jsx
> [P2-47] Admin Sales Revenue Feature

- package-lock.json
- package.json
- src/components/Admin/CardOrder/index.jsx
- src/components/Admin/ModalTerimaPesanan/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/components/Timer/index.jsx
- src/pages/checkout/index.jsx
- src/pages/konfirmasi/index.jsx
- src/pages/proses-pemesanan/index.jsx
- src/pages/upload_resep/index.jsx
- yarn.lock
> FIX: fixed visual bug in proses-pemenasan page

- src/components/Cart/index.jsx
- src/pages/alamat/index.jsx
- src/pages/keranjang/index.jsx
- src/pages/product/[productId].jsx
> bug fix and responsive

- src/components/CheckOut/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/components/Timer/index.jsx
- src/pages/checkout/index.jsx
- src/pages/konfirmasi/index.jsx
- src/pages/proses-pemesanan/index.jsx
- src/redux/reducer/price.js
> FIX: Fix bug in timer component

- src/lib/gtag.js
- src/pages/_app.jsx
> FIX: Google analytics

- .env
- src/components/Admin/CardOrder/index.jsx
- src/components/Admin/CardWithCircularBar/index.jsx
- src/components/Admin/DaftarObatTable/index.jsx
- src/components/Admin/ModalSalinanResep/index.jsx
- src/components/Admin/ModalTerimaPesanan/index.jsx
- src/components/Admin/ProductCardItems/index.jsx
- src/components/BannerJaminan/bannerJaminanBox.jsx
- src/components/BannerJaminan/index.jsx
- src/components/Cart/index.jsx
- src/components/CheckOut/index.jsx
- src/components/DaftarPemesanan/index.jsx
- src/components/MetodePembayaran/index.jsx
- src/components/Modal/index.jsx
- src/components/ModalAlamat/index.jsx
- src/components/ProductCard/index.jsx
- src/components/Timer/index.jsx
- src/pages/admin/dashboard/index.jsx
- src/pages/admin/laba-&-rugi/index.jsx
- src/pages/checkout/index.jsx
- src/pages/detail-transaksi/[transactionId].jsx
- src/pages/index.jsx
- src/pages/keranjang/index.jsx
- src/pages/konfirmasi/index.jsx
- src/pages/login/index.jsx
- src/pages/product/[productId].jsx
- src/pages/proses-pemesanan/index.jsx
@hasianamin @theodevoid tolong di merge kk ehehe
> Fix bugs, add new UI, change localestring format

- src/components/Admin/ModalTerimaPesanan/index.jsx
- src/components/Timer/index.jsx
> FIX: fixed bug in timer (not executing decline transaction when timer ran up) and accept transaction UI for admin

- src/components/Page/index.jsx
- src/config/api.js
> Semoga last

- .env
- src/pages/admin/dashboard/index.jsx
- src/pages/admin/product-details/index.jsx
> FIX report percentage

- .env
- src/pages/admin/dashboard/index.jsx
- src/pages/admin/product-details/index.jsx
> FIX: report

- src/pages/admin/dashboard/index.jsx
- src/pages/admin/product-details/index.jsx
> FIX: fix the percentage issues

- src/components/Admin/CardOrder/index.jsx
- src/components/Admin/ModalSalinanResep/index.jsx
- src/components/Admin/ModalTerimaPesanan/index.jsx
- src/pages/admin/dalam-pengiriman/index.jsx
- src/pages/admin/dibatalkan/index.jsx
- src/pages/admin/pesanan-baru/index.jsx
- src/pages/admin/product-details/index.jsx
- src/pages/admin/selesai/index.jsx
- src/pages/admin/semua-pesanan/index.jsx
- src/pages/admin/siap-dikirim/index.jsx
@hasianamin @theodevoid tolong di merge kk hihih semoga last terimakasih
> Fix modalsalinanresepui & Admin Rerendering
